/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.npower.help.action.admin.subjects;

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.DynaActionForm;
import org.apache.struts.actions.LookupDispatchAction;

import com.npower.help.action.ActionHelper;
import com.npower.help.action.HelpDAOPersistentManager;
import com.npower.help.core.Subject;
import com.npower.help.core.SubjectLocale;
import com.npower.help.dao.HelpDAOFactory;
import com.npower.help.dao.SubjectDAO;

/**
 * MyEclipse Struts Creation date: 06-27-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class SaveSubjectAction extends LookupDispatchAction {
  /*
   * Generated Methods
   */
  @Override
  protected Map<String, String> getKeyMethodMap() {
    Map<String, String> map = new HashMap<String, String>();
    map.put("page.help.admin.edit4subject.page.message.save.button.lable", "save");
    return map;
  }

  public ActionForward save(ActionMapping mapping, ActionForm rawForm, HttpServletRequest request,
      HttpServletResponse response) throws Exception {
    HelpDAOFactory factory = null;
    DynaActionForm form = (DynaActionForm) rawForm;
    try {
      factory = HelpDAOPersistentManager.getManagementBeanFactory(request);

      // Load Subjects Tree
      ActionHelper.loadSubjectsTree(this.getServlet().getServletContext(), request, factory);

      SubjectDAO subjectDAO = factory.getSubjectDAO();
      String externalId = form.getString("externalId");
      String subjectId = form.getString("subjectId");
      if (StringUtils.isNotEmpty(subjectId)) {
        Subject subject = subjectDAO.findById(Long.parseLong(subjectId));
        subject.setExternalId(externalId);
        factory.beginTransaction();
        subjectDAO.save(subject);
        factory.commit();
        request.setAttribute("subject", subject);
      } else {
        Subject subject = subjectDAO.newInstance();
        subject.setExternalId(externalId);
        factory.beginTransaction();
        subjectDAO.save(subject);
        factory.commit();
        request.setAttribute("subject", subject);
      }
      SubjectLocale defaultLocale = ActionHelper.getDefaultSubjectLocale(factory);
      request.setAttribute("defaultLocale", defaultLocale);
    } catch (Exception e) {
      if (factory != null) {
        factory.rollback();
      }
      throw e;
    }
    return mapping.findForward("save");
  }

  public ActionForward unspecified(ActionMapping mapping, ActionForm rawForm, HttpServletRequest request,
      HttpServletResponse response) throws Exception {
    return this.save(mapping, rawForm, request, response);
  }
}