/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.npower.help.action.admin.subjects;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.DynaActionForm;
import org.apache.struts.util.LabelValueBean;

import com.npower.help.action.ActionHelper;
import com.npower.help.action.HelpDAOPersistentManager;
import com.npower.help.core.Subject;
import com.npower.help.core.SubjectLocale;
import com.npower.help.dao.HelpDAOFactory;
import com.npower.help.dao.SubjectDAO;
import com.npower.help.dao.SubjectLocaleDAO;

/**
 * MyEclipse Struts Creation date: 06-25-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class SelectLocalAction extends Action {

  /**
   * Method execute
   * 
   * @param mapping
   * @param form
   * @param request
   * @param response
   * @return ActionForward
   */
  public ActionForward execute(ActionMapping mapping, ActionForm rawForm, HttpServletRequest request,
      HttpServletResponse response) throws Exception {
    HelpDAOFactory factory = null;
    DynaActionForm form = (DynaActionForm) rawForm;
    try {
      factory = HelpDAOPersistentManager.getManagementBeanFactory(request);
      SubjectDAO subjectDAO = factory.getSubjectDAO();
      SubjectLocaleDAO localeDAO = factory.getSubjectLocaleDAO();

      // Load Subjects Tree
      ActionHelper.loadSubjectsTree(this.getServlet().getServletContext(), request, factory);

      String subjectId = form.getString("subjectId");
      Subject subject = subjectDAO.findById(Long.parseLong(subjectId));
      request.setAttribute("subject", subject);

      String localeId = form.getString("localeId");
      SubjectLocale currentLocale = localeDAO.findById(localeId);
      request.setAttribute("currentLocale", currentLocale);

      // 获得本地语言
      List<Object> localeList = new ArrayList<Object>();
      for (Locale locale : Locale.getAvailableLocales()) {
        localeList.add(new LabelValueBean(locale.getDisplayName(), locale.toString()));
      }
      request.setAttribute("localeList", localeList);
    } catch (Exception e) {
      throw e;
    }
    return mapping.findForward("view");
  }
}