/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.npower.unicom.action;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.DynaValidatorForm;

import com.npower.dm.action.BaseDispatchAction;
import com.npower.dm.core.DMException;
import com.npower.unicom.ExportReportDAO;
import com.npower.unicom.VCPCDRLog;


/** 
 * MyEclipse Struts
 * Creation date: 11-03-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class CreateReportAction extends BaseDispatchAction{
  /*
   * Generated Methods
   */

  /** 
   * Method execute
   * @param mapping
   * @param form
   * @param request
   * @param response
   * @return ActionForward
   * @throws DMException 
   * @throws ParseException 
   */
  public ActionForward query4Time(ActionMapping mapping, ActionForm form, HttpServletRequest request,
      HttpServletResponse response) throws DMException, ParseException {
    DynaValidatorForm rawForm = (DynaValidatorForm) form;
    String startTime = rawForm.getString("startTime");
    String endTime = rawForm.getString("endTime");
    
    DateFormat df = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
    DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
    startTime = formatter.format(df.parse(startTime));
    endTime = formatter.format(df.parse(endTime));
    
    
    ExportReportDAO dao = new ExportReportDAO(this.getManagementBeanFactory(request), null);
    List<VCPCDRLog> dateTime = dao.getReport4Time(startTime, endTime);
    request.setAttribute("result", dateTime);
    return mapping.findForward("dateTime");
  }
  
  
  /** 
   * Method execute
   * @param mapping
   * @param form
   * @param request
   * @param response
   * @return ActionForward
   * @throws DMException 
   */
  public ActionForward sendAQuery(ActionMapping mapping, ActionForm form, HttpServletRequest request,
      HttpServletResponse response) throws DMException {    
    Calendar calendar = Calendar.getInstance();
    DateFormat df = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
    String nowDate = df.format(calendar.getTime());
    String year = Integer.toString(calendar.get(Calendar.YEAR));
    String month = Integer.toString(calendar.get(Calendar.MONTH)+1);
    String day = Integer.toString(calendar.get(Calendar.DATE));
    
    if (month.length() == 1 ) {
      month = "0" + month;
      
    }
    if (day.length() == 1) {
      day = "0" + day;
    }
    
    
    String nowdate1 = month+"/"+day+"/"+year+" 00:00:00";
    request.setAttribute("nowDate", nowDate);
    request.setAttribute("nowdate1", nowdate1);
    return mapping.findForward("time");
  }

}