/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.npower.help.action.show.subjects;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.DynaActionForm;

import com.npower.help.action.ActionHelper;
import com.npower.help.action.HelpDAOPersistentManager;
import com.npower.help.action.ShowActionHelper;
import com.npower.help.core.Subject;
import com.npower.help.core.SubjectContent;
import com.npower.help.core.SubjectLocale;
import com.npower.help.dao.HelpDAOFactory;
import com.npower.help.dao.SubjectContentDAO;
import com.npower.help.dao.SubjectDAO;
import com.npower.help.dao.SubjectLocaleDAO;

/**
 * MyEclipse Struts Creation date: 07-07-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class ShowSubject4ContentAction extends Action {
  /*
   * Generated Methods
   */

  /**
   * Method execute
   * 
   * @param mapping
   * @param form
   * @param request
   * @param response
   * @return ActionForward
   */
  public ActionForward execute(ActionMapping mapping, ActionForm rawForm, HttpServletRequest request,
      HttpServletResponse response) throws Exception {
    HelpDAOFactory factory = null;
    DynaActionForm form = (DynaActionForm) rawForm;
    try {
      factory = HelpDAOPersistentManager.getManagementBeanFactory(request);
      SubjectDAO subjectDAO = factory.getSubjectDAO();
      SubjectLocaleDAO localeDAO = factory.getSubjectLocaleDAO();
      SubjectContentDAO contentDAO = factory.getSubjectContentDAO();
      // Load Subjects Tree
      ShowActionHelper.loadShowSubjectsTree(this.getServlet().getServletContext(), request, factory);
      // 获取Subject
      String subjectId = form.getString("subjectId");
      Subject subject = subjectDAO.findById(Long.parseLong(subjectId));
      // 获取Location
      List<Subject> subjects4Location = new ArrayList<Subject>();
      Subject location = subject;
      while (location != null) {
        subjects4Location.add(0, location);
        location = location.getParent();
      }
      // 获取当前主题下的子主题
      List<Subject> childList = new ArrayList<Subject>();
      for (Subject child : subject.getChildren()) {
        childList.add(child);
      }
      if (childList != null) {
        request.setAttribute("childList", childList);
      }
      // 提取SubjectLocale
      String localeId = form.getString("localeId");
      SubjectLocale currentLocale = ActionHelper.getDefaultSubjectLocale(factory);
      if (StringUtils.isNotEmpty(localeId)) {
        currentLocale = localeDAO.findById(localeId);
      }
      request.setAttribute("locale", currentLocale);
      // 当前Subject的Locale列表
      Set<SubjectLocale> localeList = new HashSet<SubjectLocale>();
      localeList.add(currentLocale);
      for (SubjectContent content : subject.getSubjectContents()) {
        localeList.add(content.getSubjectLocale());
      }

      SubjectContent subjectContent = contentDAO.getSubjectContent(subject, currentLocale);
      request.setAttribute("currentLocale", currentLocale);
      request.setAttribute("subjectContent", subjectContent);
      request.setAttribute("localeList", localeList);
      request.setAttribute("subject", subject);
      request.setAttribute("subjects4Location", subjects4Location);
    } catch (Exception e) {
      throw e;
    }
    return mapping.findForward("view");
  }

}