package com.npower.help.hibernate.entity;

import java.util.HashSet;
import java.util.Set;

import com.npower.help.core.SubjectContent;
import com.npower.help.core.SubjectLocale;

/**
 * AbstractSubjectLocale generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSubjectLocale implements java.io.Serializable, SubjectLocale {

  // Fields

  private String              id;

  private String              language;

  private String              country;

  private Set<SubjectContent> subjectContents = new HashSet<SubjectContent>(0);

  // Constructors

  /** default constructor */
  public AbstractSubjectLocale() {
  }

  /** minimal constructor */
  public AbstractSubjectLocale(String id, String language) {
    this.id = id;
    this.language = language;
  }

  /** full constructor */
  public AbstractSubjectLocale(String id, String language, String country, Set<SubjectContent> subjectContents) {
    this.id = id;
    this.language = language;
    this.country = country;
    this.subjectContents = subjectContents;
  }

  // Property accessors

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectLocale#getId()
   */
  public String getId() {
    return this.id;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectLocale#setId(java.lang.String)
   */
  public void setId(String id) {
    this.id = id;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectLocale#getLanguage()
   */
  public String getLanguage() {
    return this.language;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectLocale#setLanguage(java.lang.String)
   */
  public void setLanguage(String language) {
    this.language = language;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectLocale#getCountry()
   */
  public String getCountry() {
    return this.country;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectLocale#setCountry(java.lang.String)
   */
  public void setCountry(String country) {
    this.country = country;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectLocale#getSubjectContents()
   */
  public Set<SubjectContent> getSubjectContents() {
    return this.subjectContents;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectLocale#setSubjectContents(java.util.Set)
   */
  public void setSubjectContents(Set<SubjectContent> subjectContents) {
    this.subjectContents = subjectContents;
  }

}