package com.npower.help.hibernate.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.npower.help.core.Subject;
import com.npower.help.core.SubjectContent;
import com.npower.help.core.SubjectImage;
import com.npower.help.core.SubjectLocale;

/**
 * AbstractSubjectContent generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSubjectContent implements java.io.Serializable, SubjectContent {

  // Fields

  private long                id;

  private Subject             subject;

  private SubjectLocaleEntity subjectLocale;

  private String              name;

  private String              description;

  private String              keywords;

  private String              content;

  private Date                lastUpdatedTime;

  private Date                lastUpdatedBy;

  private Set<SubjectImage>   subjectImages = new HashSet<SubjectImage>(0);

  // Constructors

  /** default constructor */
  public AbstractSubjectContent() {
  }

  /** minimal constructor */
  public AbstractSubjectContent(Long id, Subject subject, SubjectLocaleEntity subjectLocale, String name,
      Date lastUpdatedTime) {
    this.id = id;
    this.subject = subject;
    this.subjectLocale = subjectLocale;
    this.name = name;
    this.lastUpdatedTime = lastUpdatedTime;
  }

  /** full constructor */
  public AbstractSubjectContent(Long id, Subject subject, SubjectLocaleEntity subjectLocale, String name,
      String description, String keywords, String content, Date lastUpdatedTime, Date lastUpdatedBy,
      Set<SubjectImage> subjectImages) {
    this.id = id;
    this.subject = subject;
    this.subjectLocale = subjectLocale;
    this.name = name;
    this.description = description;
    this.keywords = keywords;
    this.content = content;
    this.lastUpdatedTime = lastUpdatedTime;
    this.lastUpdatedBy = lastUpdatedBy;
    this.subjectImages = subjectImages;
  }

  // Property accessors

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectContent#getId()
   */
  public long getId() {
    return this.id;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectContent#setId(java.lang.Long)
   */
  public void setId(long id) {
    this.id = id;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectContent#getSubject()
   */
  public Subject getSubject() {
    return this.subject;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectContent#setSubject(com.npower.help.dao.SubjectEntity)
   */
  public void setSubject(Subject subject) {
    this.subject = subject;
    if (subject != null) {
      // this.subject.getSubjectContents().add(this);
    }
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectContent#getSubjectLocale()
   */
  public SubjectLocaleEntity getSubjectLocale() {
    return this.subjectLocale;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectContent#setSubjectLocale(com.npower.help.dao.SubjectLocaleEntity)
   */
  public void setSubjectLocale(SubjectLocale subjectLocale) {
    this.subjectLocale = (SubjectLocaleEntity) subjectLocale;
    if (subjectLocale != null) {
      // this.subjectLocale.getSubjectContents().add(this);
    }
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectContent#getName()
   */
  public String getName() {
    return this.name;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectContent#setName(java.lang.String)
   */
  public void setName(String name) {
    this.name = name;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectContent#getDescription()
   */
  public String getDescription() {
    return this.description;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectContent#setDescription(java.lang.String)
   */
  public void setDescription(String description) {
    this.description = description;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectContent#getKeyeords()
   */
  public String getKeywords() {
    return this.keywords;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectContent#setKeyeords(java.lang.String)
   */
  public void setKeywords(String keywords) {
    this.keywords = keywords;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectContent#getContent()
   */
  public String getContent() {
    return this.content;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectContent#setContent(java.lang.String)
   */
  public void setContent(String content) {
    this.content = content;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectContent#getLastUpdatedTime()
   */
  public Date getLastUpdatedTime() {
    return this.lastUpdatedTime;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectContent#setLastUpdatedTime(java.util.Date)
   */
  public void setLastUpdatedTime(Date lastUpdatedTime) {
    this.lastUpdatedTime = lastUpdatedTime;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectContent#getLastUpdatedBy()
   */
  public Date getLastUpdatedBy() {
    return this.lastUpdatedBy;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectContent#setLastUpdatedBy(java.util.Date)
   */
  public void setLastUpdatedBy(Date lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectContent#getSubjectImages()
   */
  public Set<SubjectImage> getSubjectImages() {
    return this.subjectImages;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectContent#setSubjectImages(java.util.Set)
   */
  public void setSubjectImages(Set<SubjectImage> subjectImages) {
    this.subjectImages = subjectImages;
  }

}