package com.npower.help.hibernate.entity;

import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;

import org.hibernate.Hibernate;

import com.npower.help.core.SubjectContent;
import com.npower.help.core.SubjectImage;

/**
 * AbstractSubjectImage generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSubjectImage implements java.io.Serializable, SubjectImage {

  // Fields

  private long           imageId;

  private SubjectContent subjectContent;

  private String         mimeType;

  private Blob           binary;

  private String         description;

  private String         filename;

  private long           width;

  private long           heigth;

  // Constructors

  /** default constructor */
  public AbstractSubjectImage() {
  }

  /** minimal constructor */
  public AbstractSubjectImage(long imageId, SubjectContentEntity subjectContent, String mimeType, Blob binary) {
    this.imageId = imageId;
    this.subjectContent = subjectContent;
    this.mimeType = mimeType;
    this.binary = binary;
  }

  /** full constructor */
  public AbstractSubjectImage(long imageId, SubjectContentEntity subjectContent, String mimeType, Blob binary,
      String description, String filename, long width, long heigth) {
    this.imageId = imageId;
    this.subjectContent = subjectContent;
    this.mimeType = mimeType;
    this.binary = binary;
    this.description = description;
    this.filename = filename;
    this.width = width;
    this.heigth = heigth;
  }

  // Property accessors

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectImage#getImageId()
   */
  public long getImageId() {
    return this.imageId;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectImage#setImageId(java.lang.Long)
   */
  public void setImageId(long imageId) {
    this.imageId = imageId;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectImage#getSubjectContent()
   */
  public SubjectContent getSubjectContent() {
    return this.subjectContent;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectImage#setSubjectContent(com.npower.help.dao.SubjectContentEntity)
   */
  public void setSubjectContent(SubjectContent subjectContent) {
    this.subjectContent = subjectContent;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectImage#getMimeType()
   */
  public String getMimeType() {
    return this.mimeType;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectImage#setMimeType(java.lang.String)
   */
  public void setMimeType(String mimeType) {
    this.mimeType = mimeType;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectImage#getBinary()
   */
  public Blob getBinary() {
    return this.binary;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectImage#setBinary(java.sql.Blob)
   */
  public void setBinary(Blob binary) {
    this.binary = binary;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectImage#setBinary(java.io.InputStream)
   */
  public void setBinary(InputStream in) throws IOException {
    this.setBinary(Hibernate.createBlob(in));
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectImage#getDescription()
   */
  public String getDescription() {
    return this.description;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectImage#setDescription(java.lang.String)
   */
  public void setDescription(String description) {
    this.description = description;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectImage#getFilename()
   */
  public String getFilename() {
    return this.filename;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectImage#setFilename(java.lang.String)
   */
  public void setFilename(String filename) {
    this.filename = filename;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectImage#getWidth()
   */
  public long getWidth() {
    return this.width;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectImage#setWidth(java.lang.Long)
   */
  public void setWidth(long width) {
    this.width = width;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectImage#getHeigth()
   */
  public long getHeigth() {
    return this.heigth;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.help.dao.SubjectImage#setHeigth(java.lang.Long)
   */
  public void setHeigth(long heigth) {
    this.heigth = heigth;
  }

}