package com.npower.help.hibernate.entity;

import com.npower.help.core.Subject;

// Generated by MyEclipse Persistence Tools

/**
 * SubjectEntity generated by MyEclipse Persistence Tools
 */
public class SubjectEntity extends AbstractSubject implements java.io.Serializable {

  // Constructors

  /**
   * 
   */
  private static final long serialVersionUID = 1L;

  /** default constructor */
  public SubjectEntity() {
  }

  /** minimal constructor */
  public SubjectEntity(Long subjectId, String externalId) {
    super(subjectId, externalId);
  }

  public boolean isAncestors(Subject child) {
    boolean falg = true;
    if (this == child) {
      falg = false;
    }

    while (child.getParent() != null) {
      if (child.getParent() == this) {
        falg = false;
      }
      child = child.getParent();
    }
    return falg;
  }

}
