package com.npower.help.hibernate.entity;

// Generated by MyEclipse Persistence Tools

import java.util.Date;
import java.util.Set;

import com.npower.help.core.SubjectImage;

/**
 * SubjectContentEntity generated by MyEclipse Persistence Tools
 */
public class SubjectContentEntity extends AbstractSubjectContent implements java.io.Serializable {

  // Constructors

  /**
   * 
   */
  private static final long serialVersionUID = 1L;

  /** default constructor */
  public SubjectContentEntity() {
  }

  /** minimal constructor */
  public SubjectContentEntity(Long id, SubjectEntity subject, SubjectLocaleEntity subjectLocale, String name,
      Date lastUpdatedTime) {
    super(id, subject, subjectLocale, name, lastUpdatedTime);
  }

  /** full constructor */
  public SubjectContentEntity(Long id, SubjectEntity subject, SubjectLocaleEntity subjectLocale, String name,
      String description, String keyeords, String content, Date lastUpdatedTime, Date lastUpdatedBy,
      Set<SubjectImage> subjectImages) {
    super(id, subject, subjectLocale, name, description, keyeords, content, lastUpdatedTime, lastUpdatedBy,
        subjectImages);
  }
}
