package com.npower.help.hibernate.entity;

// Generated by MyEclipse Persistence Tools

import java.util.Set;

import com.npower.help.core.SubjectContent;

/**
 * SubjectLocaleEntity generated by MyEclipse Persistence Tools
 */
public class SubjectLocaleEntity extends AbstractSubjectLocale implements java.io.Serializable {

  // Constructors

  /**
   * 
   */
  private static final long serialVersionUID = 1L;

  /** default constructor */
  public SubjectLocaleEntity() {
  }

  /** minimal constructor */
  public SubjectLocaleEntity(String id, String language) {
    super(id, language);
  }

  /** full constructor */
  public SubjectLocaleEntity(String id, String language, String country, Set<SubjectContent> subjectContents) {
    super(id, language, country, subjectContents);
  }

}
