/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.npower.dm.action.ota.omacp;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.DynaValidatorForm;

import com.npower.dm.action.ActionHelper;
import com.npower.dm.action.BaseAction;
import com.npower.wap.omacp.parameters.AddrType;


/** 
 * MyEclipse Struts
 * Creation date: 11-17-2006
 * 
 * XDoclet definition:
 * @struts.action path="/notification/send" name="NotificationForm" input="/notification/input" scope="request" validate="true"
 * @struts.action-forward name="success" path="aaaaa" contextRelative="true"
 */
public class InputAction extends BaseAction {
  
  /** 
   * Method execute
   * @param mapping
   * @param form
   * @param request
   * @param response
   * @return ActionForward
   */
  public ActionForward execute(ActionMapping mapping, ActionForm rawForm, HttpServletRequest request,
      HttpServletResponse response) throws Exception {
    
    DynaValidatorForm form = (DynaValidatorForm)rawForm;
    
    request.setAttribute("carrierOptions", ActionHelper.getCarrierOptions(this.getManagementBeanFactory(request)));
    try {
        String defaultForward = "general";
        String applicationID = form.getString("cp_type");
        if (StringUtils.isNotEmpty(applicationID)) {
           defaultForward = applicationID.toLowerCase();
        }
        
        // Set default value
        form.set("OTAOMA_NAPDEF_BEARER", "GSM-GPRS");
        form.set("OTAOMA_NAPDEF_NAPAUTHINFO_AUTHTYPE", "PAP");
        form.set("OTAOMA_PXLOGICAL_PXPHYSICAL_PORT_PORTNBR", "9201");
        form.set("OTAOMA_EMAIL_APPID", "110");
        form.set("OTAOMA_EMAIL_SMTPAUTH", new Boolean(true));
        form.set("OTAOMA_EMAIL_STARTTLS", new Boolean(false));
        form.set("OTAOMA_EMAIL_OUTADDR_PORTNBR", "25");
        form.set("OTAOMA_EMAIL_INADDR_PORTNBR", form.getString("OTAOMA_EMAIL_APPID"));
        //form.set("OTAPINTYPE", "USERPIN");
        form.set("OTAOMA_SYNCML_CONTACTS_URI", "./cards");
        form.set("OTAOMA_SYNCML_CONTACTS_NAME", "Contacts");
        form.set("OTAOMA_SYNCML_CALENDAR_URI", "./cal");
        form.set("OTAOMA_SYNCML_CALENDAR_NAME", "Calendar");
        form.set("OTAOMA_SYNCML_NOTES_URI", "./notes");
        form.set("OTAOMA_SYNCML_NOTES_NAME", "Notes");
        form.set("OTAOMA_POC_ADDR_TYPE", AddrType.IPV4.toString());
        
        ActionForward forward = new ActionForward("tile.ota.omacp.input." + defaultForward, false);
        return forward;
    } catch (Exception e) {
      throw e;
    } finally {
    }
  }
  
}