/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.npower.dm.action.model;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.DynaActionForm;

import com.npower.dm.action.BaseAction;
import com.npower.dm.core.ModelClassification;
import com.npower.dm.management.ManagementBeanFactory;
import com.npower.dm.management.ModelClassificationBean;

/**
 * MyEclipse Struts Creation date: 09-09-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class ModelClassification4DeleteAction extends BaseAction {
  /*
   * Generated Methods
   */

  /**
   * Method execute
   * 
   * @param mapping
   * @param form
   * @param request
   * @param response
   * @return ActionForward
   */
  public ActionForward execute(ActionMapping mapping, ActionForm Rowform, HttpServletRequest request,
      HttpServletResponse response) throws Exception {
    DynaActionForm form = (DynaActionForm) Rowform;
    String id = form.getString("id");
    ManagementBeanFactory factory = null;
    try {
      factory = this.getManagementBeanFactory(request);
      ModelClassificationBean bean = factory.createModelClassificationBean();
      ModelClassification mc = bean.getModelClassificationByID(Long.parseLong(id));
      factory.beginTransaction();
      bean.delete(mc);
      factory.commit();
    } catch (Exception e) {
      if (factory != null) {
        factory.rollback();
      }
      throw e;
    }
    return mapping.findForward("delete");
  }
}