/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.npower.dm.action.model;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.DynaActionForm;

import com.npower.dm.action.BaseAction;
import com.npower.dm.core.ModelClassification;
import com.npower.dm.core.selector.NullModelSelector;
import com.npower.dm.management.ManagementBeanFactory;
import com.npower.dm.management.ModelClassificationBean;

/**
 * MyEclipse Struts Creation date: 09-08-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class ModelClassification4SaveAction extends BaseAction {
  /*
   * Generated Methods
   */

  /**
   * Method execute
   * 
   * @param mapping
   * @param form
   * @param request
   * @param response
   * @return ActionForward
   */
  public ActionForward execute(ActionMapping mapping, ActionForm Rowform, HttpServletRequest request,
      HttpServletResponse response) throws Exception {
    DynaActionForm form = (DynaActionForm) Rowform;
    String id = form.getString("id");
    String name = form.getString("name");
    String externalID = form.getString("externalID");
    String description = form.getString("description");
    ManagementBeanFactory factory = null;
    try {
      factory = this.getManagementBeanFactory(request);
      ModelClassificationBean bean = factory.createModelClassificationBean();
      NullModelSelector selector = new NullModelSelector();
      factory.beginTransaction();
      if (StringUtils.isNotEmpty(id)) {
        ModelClassification mc = bean.getModelClassificationByID(Long.parseLong(id));
        mc.setName(name);
        mc.setExternalID(externalID);
        mc.setModelSelector(selector);
        mc.setDescription(description);
        bean.update(mc);
      } else {
        ModelClassification mc = bean.newInstance(externalID, name, selector);
        mc.setDescription(description);
        bean.update(mc);
      }
      factory.commit();
    } catch (Exception e) {
      if (factory != null) {
        factory.rollback();
      }
      throw e;
    }
    return mapping.findForward("edit");
  }
}