/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.npower.dm.action.favorite;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.npower.dm.action.BaseAction;
import com.npower.dm.action.Constants;
import com.npower.dm.core.Favorite;
import com.npower.dm.hibernate.dao.FavoriteBeanImpl;
import com.npower.dm.management.FavoriteBean;
import com.npower.dm.management.ManagementBeanFactory;
import com.npower.dm.security.DMWebPrincipal;

/**
 * MyEclipse Struts Creation date: 12-17-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class FavoritesAction extends BaseAction {
  /*
   * Generated Methods
   */

  /**
   * Method execute
   * 
   * @param mapping
   * @param form
   * @param request
   * @param response
   * @return ActionForward
   */
  public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request,
      HttpServletResponse response) throws Exception {
    Boolean share = true;
    ManagementBeanFactory factory = null;
    DMWebPrincipal user = (DMWebPrincipal) request.getSession().getAttribute(Constants.ADMIN_USER_KEY);
    String owner = user.getUsername();
    try {
      factory = this.getManagementBeanFactory(request);
      FavoriteBean favoriteBean = (FavoriteBean) factory.createBean(FavoriteBeanImpl.class);
      List<Favorite> favorites = favoriteBean.findByOwner(owner);
      for (Favorite favorite : favoriteBean.findByIsshare(share)) {
        if (!favorite.getOwner().equals(owner)) {
          favorites.add(favorite);
        }
      }
      request.setAttribute("favorites", favorites);
      request.setAttribute("currentOwner", owner);
    } catch (Exception e) {
      throw e;
    }
    return mapping.findForward("list");
  }

}
