/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.npower.dm.action.favorite;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.DynaValidatorForm;

import com.npower.dm.action.BaseDispatchAction;
import com.npower.dm.core.FavoriteDevice;
import com.npower.dm.hibernate.dao.FavoriteDeviceBeanImpl;
import com.npower.dm.management.FavoriteDeviceBean;
import com.npower.dm.management.ManagementBeanFactory;

/** 
 * MyEclipse Struts
 * Creation date: 01-15-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class RemoveDeviceAction extends BaseDispatchAction {
  /*
   * Generated Methods
   */

  private static Log log = LogFactory.getLog(RemoveDeviceAction.class);
  
  /** 
   * Method execute
   * @param mapping
   * @param form
   * @param request
   * @param response
   * @return ActionForward
   */
  public ActionForward remove(ActionMapping mapping, ActionForm form, HttpServletRequest request,
      HttpServletResponse response) throws Exception {
    DynaValidatorForm favoriteForm = (DynaValidatorForm) form;
    String deviceId = favoriteForm.getString("deviceId");
    log.debug("DeviceID:" + deviceId);
    ManagementBeanFactory factory = null;
    try {
      factory = this.getManagementBeanFactory(request);
      FavoriteDeviceBean favoriteDeviceBean = (FavoriteDeviceBean)factory.createBean(FavoriteDeviceBeanImpl.class);
      for (FavoriteDevice favoriteDevice : favoriteDeviceBean.findByDeviceId(Long.parseLong(deviceId))){
        factory.beginTransaction();
        favoriteDeviceBean.delete(favoriteDevice);
        factory.commit();
      }
    } catch (Exception e) {
      throw e;
    }
    return mapping.findForward("remove");
  }
}