/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.npower.dm.action.favorite;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.DynaValidatorForm;

import com.npower.dm.action.BaseDispatchAction;
import com.npower.dm.core.Device;
import com.npower.dm.core.Favorite;
import com.npower.dm.core.FavoriteDevice;
import com.npower.dm.hibernate.dao.FavoriteBeanImpl;
import com.npower.dm.hibernate.dao.FavoriteDeviceBeanImpl;
import com.npower.dm.hibernate.management.DeviceManagementBeanImpl;
import com.npower.dm.management.DeviceBean;
import com.npower.dm.management.FavoriteBean;
import com.npower.dm.management.FavoriteDeviceBean;
import com.npower.dm.management.ManagementBeanFactory;

/** 
 * MyEclipse Struts
 * Creation date: 12-18-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ViewFavoriteAction extends BaseDispatchAction {
  /*
   * Generated Methods
   */

  /** 
   * Method execute
   * @param mapping
   * @param form
   * @param request
   * @param response
   * @return ActionForward
   */
  public ActionForward view(ActionMapping mapping, ActionForm form, HttpServletRequest request,
      HttpServletResponse response) throws Exception {
    DynaValidatorForm favoriteForm = (DynaValidatorForm) form;
    String favoriteId = favoriteForm.getString("favoriteId");
    if (StringUtils.isEmpty(favoriteId)) {
      favoriteId = (String) request.getParameter("favoriteId");
    }
    ManagementBeanFactory factory = null;
    try {
      factory = this.getManagementBeanFactory(request);
      FavoriteBean favoriteBean = (FavoriteBean)factory.createBean(FavoriteBeanImpl.class);
      FavoriteDeviceBean favoriteDeviceBean = (FavoriteDeviceBean)factory.createBean(FavoriteDeviceBeanImpl.class);
      DeviceBean deviceBean = (DeviceBean)factory.createBean(DeviceManagementBeanImpl.class);
      Favorite favorite = favoriteBean.findById(Long.parseLong(favoriteId));
      List<FavoriteDevice> favoriteDeviceList = favoriteDeviceBean.findByProperty("favorite", favorite);
      List<Device> deviceList = new ArrayList<Device>();
      for (FavoriteDevice favoriteDevice : favoriteDeviceList) {
        long deviceId = favoriteDevice.getDeviceId();
        Device device = deviceBean.getDeviceByID(deviceId);
        deviceList.add(device);
      }
      request.setAttribute("favorite", favorite);
      request.setAttribute("devices", deviceList);
      request.setAttribute("favoriteId", favoriteId);
    } catch (Exception e) {
      throw e;
    }
    return mapping.findForward("view");
  }
}