CREATE TABLESPACE OTASDM
    LOGGING
    DATAFILE '/insignia/oracle/oradata/orcl/OTASDM.ora' SIZE 10M EXTENT
    MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO
;

ALTER DATABASE DATAFILE '/insignia/oracle/oradata/orcl/OTASDM.ora' AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

CREATE
    TEMPORARY TABLESPACE OTASDM_TMP TEMPFILE
    '/insignia/oracle/oradata/orcl/OTASDM_TMP.ora' SIZE 10M EXTENT
    MANAGEMENT LOCAL UNIFORM SIZE 1M
;

ALTER DATABASE TEMPFILE '/insignia/oracle/oradata/orcl/OTASDM_TMP.ora' AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

CREATE USER otasdm
    IDENTIFIED BY otasdm DEFAULT TABLESPACE OTASDM
    TEMPORARY TABLESPACE OTASDM_TMP
;

GRANT RESOURCE, CONNECT, DBA, CTXAPP TO otasdm;


